spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm551823
    password: 080904
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

